title: Groq Chat Plugin
description: Groq Chat Plugin for Obsidian with support for latest models
baseurl: "/groq-chat-plugin"
url: "https://semernyakov.github.io"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - demo/

languages:
  - en
  - ru

defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en
  - scope:
      path: "ru"
    values:
      lang: ru

github:
  is_project_page: true
  repository_name: groq-chat-plugin
  repository_url: https://github.com/semernyakov/groq-chat-plugin
  owner_name: semernyakov
  owner_url: https://github.com/semernyakov 